[project]
name = "gtnh-toolkit"
version = "0.1.0"
description = "Tools for your GTNH adventure"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "graphviz>=0.20.3",
    "mypy>=1.14.1",
    "pyomo>=6.8.2",
]
